spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum?createDatabaseIfNotExist=true
    username: root
    password: admin123
  jpa:
    properties:
      hibernate:
        show-sql: true
        format-sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        transport:
          protocol:
        debug:
        smtp:
          auth:
          starttls:
            enable:
  h2:
    console:
      enabled: true
jwt:
  secret: secret